INSERT INTO USUARIO VALUES (1,false,'Rodriguez Sanchez','pepe@msn.com','$2a$10$FOWqt/qsDM7iFNqq3ZdngeRCYaJjwa1/wcvjp8x5ihlB4RETxDnq.','pepito','Pepe')
INSERT INTO USUARIO VALUES (2,true,'Perez Sanchez','juan@msn.com','$2a$10$z5Aa1fLjY5x9kM2qGSoMuu1JnJ3SZ.aAXfhfwb5/ZuNt6kM2K2Yfy','nadal2015','Juan')
INSERT INTO USUARIO VALUES (3,false,'Juarez Dominguez','luis@msn.com','$2a$10$D8YOJHw8tA2B/FCyIbTZIeNV5VZRmfOKG3NGBTQUqijTuREMK1476','archer','Luis')
INSERT INTO USUARIO VALUES (4,false,'Rodriguez sanchez','perico@msn.com','$2a$10$NGU7XbNviOnNsqA6eXpvPuxnSGuEMGIqR3DuqJax4xLJraZreMEyG','RMFC','Sergio')
INSERT INTO CONCEPTO VALUES (1,false,'examen 2015','examen SO',4,'examen',1)
INSERT INTO CONCEPTO VALUES (2,true,'teoria 2010','teoriaclase SO',8,'teoria',1)
INSERT INTO CONCEPTO VALUES (3,false,'teoria matematicas','teorcapasada',32,'teoria',4)
INSERT INTO SOLUCION VALUES (1,'solucion muy bien solucionada','false','das2',10,1,4)
INSERT INTO SOLUCION VALUES (2,'solucion muy mala','true','das',-3,1,3)
INSERT INTO SOLUCION VALUES (3,'solucion muy bien solucionada','false','das3',16,1,1)
INSERT INTO TAG VALUES (1,'SO')
INSERT INTO TAG VALUES (2,'2015')
INSERT INTO TAG VALUES (3,'Matemáticas')
INSERT INTO TAGEO VALUES (1,1,1)
INSERT INTO TAGEO VALUES (2,1,2)
INSERT INTO TAGEO VALUES (3,2,1)
INSERT INTO TAGEO VALUES (4,2,2)
INSERT INTO TAGEO VALUES (5,3,3)